In [1]:
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
from openai import OpenAI
openai_client = OpenAI()

In [3]:
import numpy as np

def cosine_similarity(vec1, vec2):
    """
    Calculate the cosine similarity between two vectors.

    Parameters:
    vec1 (numpy.array): First vector.
    vec2 (numpy.array): Second vector.

    Returns:
    float: Cosine similarity between vec1 and vec2.
    """
    dot_product = np.dot(vec1, vec2)
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)

    if norm_vec1 == 0 or norm_vec2 == 0:
        return 0.0
    return dot_product / (norm_vec1 * norm_vec2)

In [4]:
king_embedding_response = openai_client.embeddings.create(
    input="king",
    model="text-embedding-3-large"
)

king_vector = np.array(king_embedding_response.data[0].embedding)
king_vector

array([ 0.01040417,  0.02499519, -0.0014776 , ...,  0.00835009,
        0.01049861, -0.00254005])

In [5]:
queen_embedding_response = openai_client.embeddings.create(
    input="queen",
    model="text-embedding-3-large"
)

queen_vector = np.array(queen_embedding_response.data[0].embedding)
queen_vector

array([-0.01385735,  0.0008602 , -0.0167823 , ...,  0.00017693,
        0.01159847,  0.00638929])

In [6]:
king_queen_similarity = cosine_similarity(king_vector, queen_vector)
king_queen_similarity

0.5552268369726675

In [7]:
slave_embedding_response = openai_client.embeddings.create(
    input="slave",
    model="text-embedding-3-large"
)

slave_vector = np.array(slave_embedding_response.data[0].embedding)
slave_vector

array([-0.01999537,  0.00620363,  0.01191717, ...,  0.00094749,
       -0.02679118, -0.0058524 ])

In [8]:
king_slave_similarity = cosine_similarity(king_vector, slave_vector)
king_slave_similarity

0.2947745074537996

In [9]:
korean_king_embedding_response = openai_client.embeddings.create(
    input="왕",
    model="text-embedding-3-large"
)

korean_king_vector = np.array(korean_king_embedding_response.data[0].embedding)
korean_king_vector

array([-0.00595223,  0.01159333, -0.01316932, ..., -0.00357134,
        0.01323696, -0.00083999])

In [10]:
openai_king_similarity = cosine_similarity(king_vector, korean_king_vector)
openai_king_similarity

0.5474873912140233

In [11]:
from openai import OpenAI
import os

upstage_client = OpenAI(
    api_key=os.getenv("UPSTAGE_API_KEY"),
    base_url="https://api.upstage.ai/v1/solar",
)

In [12]:
upstage_king_response = upstage_client.embeddings.create(
    input="king",
    model="solar-embedding-1-large-query",
)

upstage_king_vector = np.array(upstage_king_response.data[0].embedding)

In [13]:
upstage_korean_king_response = upstage_client.embeddings.create(
    input="왕",
    model="solar-embedding-1-large-query",
)

upstage_korean_king_vector = np.array(upstage_korean_king_response.data[0].embedding)

In [14]:
upstage_king_similarity = cosine_similarity(upstage_king_vector, upstage_korean_king_vector)
upstage_king_similarity

0.852149171074866